sdk: "/Users/alexepifanoff/repos/rhodes"
app_type: rhoelements
sdkversion: 4.1.0
name: filetransfer
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt

iphone:
  configuration: Release
  sdk: iphonesimulator7.0
  provisionprofile:
  codesignidentity: iPhone Developer
  entitlements: ""
  BundleIdentifier: com.rhomobile.filetransfer
  BundleURLScheme: filetransfer
wp8:
  productid: '4fd3b670-6f04-0131-0449-388d123eda48'
android:
  abis: [arm]
  manifest_template: 'AndroidManifest.erb'
  version: 2.3.3
  rhoelements:
    config: config/Config.xml
  capabilities:
  - motorola_browser
  - motoroladev

#paths:
#  extensions:
#  - /Users/alexepifanoff/repos/Motorola-Extensions/lib/commonAPI
#  - /Users/alexepifanoff/repos/Motorola-Extensions/neon/R2D1/RhoElementsOneExtension/extensions
#  - /Users/alexepifanoff/repos/Motorola-Extensions/extensions
#  neon: /Users/alexepifanoff/repos/Motorola-Extensions/neon
