sdkversion: "4.1.0"
name: "SdcardCapability"
version: "1.0"
vendor: "rhomobile"
build: "debug"
applog: "rholog.txt"
rhohub:
  url: "https://appstaging.rhohub.com/api/v1/"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator8.1”
  provisionprofile: 
  codesignidentity: "iPhone Developer"
  entitlements: 
  BundleIdentifier: "com.rhomobile.sdcardcapability"
  BundleURLScheme: "sdcardcapability"
wp8:
  productid: "93f72ad0-c941-0131-ad05-0023241f0ea9"
android:
  manifest_template: "AndroidManifest.erb"
  version: "4.2.2"
  ajax_api_bridge: false
extensions:
  - mediaplayer
  - audiocapture
  - indicators
  - signature
wm:
app_type: "rhoelements"
#capabilities: ["read_sdcard"]
#capabilities: ["sdcard"]

