#sdk: "../../../../rhodes"
name: framework_spec
bbver: 4.6
applog: rholog.txt
version: 1.0.0
vendor: rhomobile
sdkversion: 1.4
build: release
#wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
iphone: 
  sdk: latest
  entitlements: ""
  codesignidentity: ""
  configuration: Release
  #extensions: ["digest-sha1"]   
uwp:
  productid: 'b6479381-42a8-0130-78de-3caec51bd50e'
  target: 'x86'
    
android:
  version: 4.4.2
  minSdkVer: 19
win32:
  msvc: 2015
  deployqt: 1
  deploymsvc: 1
  
extensions: ["mspec", "fileutils", "zlib", "hmac", "digest", "digest-md5", "digest-sha1", "digest-sha2", "test-libs", "set", "thread", "timeout", "uri", "net-http", "fcntl", "rexml", "zlib", "openssl.so", "openssl", "ezcrypto", "bigdecimal" ]
