sdkversion: 4.0.0
name: Rho_Push_Client
version: 1.03
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.rhoconnectpushclient
  BundleURLScheme: rhoconnectpushclient
wp:
  productid: '80b879d0-16fc-0130-39e9-3c0754090a18'
symbian:
  uid: '0xe77b6fc3'
android:
  version: 4.2.2

app_type: rhoelements

motorola_license: <put_rhoelements_license_here>

extensions: ["json", "rhoconnect-client", "rhoconnect-push"]
