# Please use relative pathes
#sdk: "../../../../rhodes"
paths:
  extensions:
    - ../../../../Motorola-Extensions/build/ci/extensions
#    - ../../../../Motorola-Extensions/lib/commonAPI
#    - ../../../../Motorola-Extensions/neon/R2D1/RhoElementsOneExtension/extensions
#    - ../../../../Motorola-Extensions/extensions
#  neon: "C:/rhomobile/Motorola-Extensions/neon"
sdkversion: "3.3.2"
name: "AutoCommonSpecOther"
app_type: "rhoelements"
#app_type: rhodes
version: 1.0
vendor: "rhomobile"
build: "debug"
debug: 1
bbver: 4.6
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator6.1"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.apigeneratorspec"
  BundleURLScheme: "apigeneratorspec"
wp:
  productid: "b6479381-42a8-0130-78de-3caec51bd50e"
symbian:
  uid: "0xe1a1ef92"
android:
  version: 2.1
  capabilities:
    - native_browser
extensions: ["signature", "instrumentation", "coreapi"]