sdkversion: 5.5
name: auto_common_spec
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: latest
  provisionprofile:
  codesignidentity: "iPhone Developer"
  entitlements:
  BundleIdentifier: com.rhomobile.autocommonspec
  BundleURLScheme: autocommonspec
  extensions: ["nativeBridgeTest", "barcode", "sensor", "screenorientation", "audiocapture", "mediacapture", "appEvents", "printing", "printing_zebra"]
wp8:
  productid: 'b6479381-42a8-0130-78de-3caec51bd50e'
  extensions: ["mediacapture"]
uwp:
  productid: 'b6479381-42a8-0130-78de-3caec51bd50e'
  target: 'x86'
  extensions: 
    - "sensor"
    - "mediacapture"
symbian:
  uid: '0xe1a1ef92'
android:
  abis:
  - arm
#  - x86
#  version: 4.4.2
  extensions: 
  - "nativeBridgeTest"
  - "emdk3-manager"
  - "barcode"
  - "screenorientation"
  - "indicators"
  - "sensor"
  - "websocket"
  - "eventsource"
  - "audiocapture"
  - 'screenorientation'
  - "mediacapture"
  - "printing"
  - "printing_zebra"
  - "instrumentation"

  capabilities:
  - native_browser
wm:
  #webkit_outprocess: 1
  #use_shared_runtime: yes
  #sdk: MC3000c50b (ARMV4I)
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions: ["barcode", "screenorientation", "cardreader", "indicators", "sensor", "audiocapture", "smartCradle", "mediacapture"]
#capabilities:

extensions: ["genPropBag", "logCapture", "signature"]
