#sdk: "../../../../rhodes"
name: new_orm_spec
applog: RhoLogSpec.txt
version: 1.1
vendor: rhomobile
app_type: "rhoelements"
iphone:
  sdk: iphonesimulator8.1
  entitlements: ""
  codesignidentity: ""
  configuration: Release
wp:
  productid: 'fd55c4d0-51fa-012e-7844-6caec51bd50e'
android:
  version: 2.3.3
extensions:
- mspec
- fileutils
- json
