---
sdk: "../../../../rhodes"
name: new_orm_spec
applog: RhoLogSpec.txt
version: 1.1

vendor: rhomobile
sdkversion: 4.1

wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
iphone:
  sdk: iphonesimulator8.1
  entitlements: ""
  codesignidentity: ""
  configuration: Release

wp:
  productid: 'fd55c4d0-51fa-012e-7844-6caec51bd50e'

android:
  version: 4.4.2
  # version: 4.4.2

extensions:
- mspec
- fileutils
- json
