---
name: new_orm_spec
# sdk: "../rhodes"
sdk: "../../../../rhodes"
#applog: rholog.txt
version: 1.0.1

vendor: rhomobile
sdkversion: 4.0

wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
iphone:
  sdk: iphonesimulator6.0
  entitlements: ""
  codesignidentity: ""
  configuration: Release
#  extensions: ["barcode"]

#wm:
#  extensions: ["barcode"]

extensions:
- mspec
- fileutils
- json

wp:
  productid: 'fd55c4d0-51fa-012e-7844-6caec51bd50e'

android:
  version: 4.3
