---
#sdk: ../../../../rhodes
sdkversion: 4.1.0
name: RhoDPXApp
version: '1.0'
vendor: rhomobile
build: debug
bbver: '6.0'
applog: rholog.txt
android:
  version: 4.2.2
  capabilities:
  - motoroladev
extensions:
  - dpx
debug: 1

rhosim:
  ajax_api_bridge: true

minify:
  js: false
  css: false
