sdkversion: "4.0.0"
name: "ManualTestingJasmine"
version: "1.0"
vendor: "rhomobile"
build: "debug"
bbver: "6.0"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator6.0"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.manualtestingjasmineapp"
  BundleURLScheme: "manualtestingjasmineapp"
wp:
  productid: "b7e81210-948b-0130-d9da-0024d76525bc"
symbian:
  uid: "0xe1a8c25c"
android:
  version: "4.0.3"
  capabilities:
  - motoroladev
extensions:
  - json
  - rhoconnect-client
  - mediaplayer
app_type: "rhoelements"
#app_type: "rhodes"
capabilities:
sdk: "C:/GitHub/rhodes"
paths:
  extensions:
    - C:\GitHub\Motorola-Extensions\extensions
    - C:\GitHub\Motorola-Extensions\lib\commonAPI
    - C:\GitHub\Motorola-Extensions\neon\R2D1\RhoElementsOneExtension\extensions
  neon: C:\GitHub\Motorola-Extensions\neon
