# path to local rhodes workspace
rhodes: "../../../../rhodes"

# path to local rhoconnect workspace
rhoconnect: "../../../../rhoconnect"

# path to rhoelements
rhoelements: "../../../../Motorola-Extensions"

