# path to local rhodes workspace
rhodes: "C:/MotorolaRhoMobileSuite4.0.0.beta.43/ruby/lib/ruby/gems/1.9.1/gems/rhodes-4.0.0.beta.43"
#rhodes: "../../../../rhodes"

# path to local rhoconnect workspace
rhoconnect: "../../../../rhoconnect"

# path to rhoelements
rhoelements: "../../../../Motorola-Extensions"

# path to testsuite_root
testsuite_root: "../../../../RMS-Testing"

# ip address of the remote RC app
rc_stack_address: 192.168.1.140
rc_stack_port: 9292
# ip address of the remote RC Push Server
rc_push_server_address: 192.168.1.140
rc_push_server_port: 8675
# address of the mobile device
device_address: 192.168.1.133
# device OS platform (wm, ce)
device_os: wm
