chdir File.dirname(__FILE__)
namespace :run do
  namespace :android do
    namespace :rb do
      desc "Run Rhoconnect Push Service specs on android device for Ruby rhodes app"
      task :rps do
        status = exec("mspec android_push_rb_spec.rb")
        exit status

        # require 'mspec'        
        # MSpec.register_files [ File.join(File.dirname(__FILE__), 'android_push_rb_spec.rb') ]
        # MSpec.store(:push_type, 'rhoconnect_push')
        # MSpec.process
        # exit_code = MSpec.exit_code
        # exit exit_code
      end

      desc "Run Google Cloud Messaging specs on android device for Ruby rhodes app"
      task :gcm do
        status = exec("mspec android_push_rb_spec.rb 'gcm'")
        exit status

        # require 'mspec'
        # MSpec.register_files [ File.join(File.dirname(__FILE__), 'android_push_rb_spec.rb') ]
        # MSpec.store(:push_type, 'gcm')
        # MSpec.process
        # exit_code = MSpec.exit_code
        # exit exit_code
      end
    end

    namespace :js do
      desc "Run Rhoconnect Push Service specs on android device for JavaScript rhodes app"
      task :rps do
        ARGV[0] = "rhoconnect_push"
        require_relative 'android_push_js_spec.rb'  
      end
    
      desc "Run Google Cloud Messaging specs on android device for JavaScript rhodes app"
      task :gcm do
        ARGV[0] = "gcm"
        require_relative 'android_push_js_spec.rb'
      end    
    end
  end
end

