sdkversion: "3.5.0"
name: "RETestAPP"
motorola_license: "`JLBrUlV`2Vxd_tMPV1kHMjBVV5%@{x0THE_TMD7SHO6D0C(b@lEbi75P.A)mLgqJhw+qDssIpla.6;X"
version: "1.0"
vendor: "rhomobile"
build: "debug"
debug: 1
bbver: "4.6"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator6.1"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.retestapp"
  BundleURLScheme: "retestapp"
  emulatortarget: "iphone"
wp:
  productid: "dc201bf1-e2e9-012f-10dc-00216a8a58d0"
wm:
#sdk: "MC3000c50b (ARMV4I)"
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
#sdk: "Windows Mobile 6 Professional SDK (ARMV4I)"

#use_shared_runtime: 1
symbian:
  uid: "0xe01c7e9f"
android:
  capabilities: 
#- non_motorola_device
  version: "2.3.4"
extensions:
  - json
#- another-extension
app_type: "rhoelements"
capabilities:
#- native_browser
  - motorola_browser
