#sdk: "/Users/mva/.rvm/gems/ruby-1.9.3-p392/gems/rhodes-4.0.0.beta.71"
sdkversion: 4.0.0
name: androidIssue
version: 1.0
vendor: rhomobile
build: debug
bbver: 6.0
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator6.1
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.androidissue
  BundleURLScheme: androidissue
wp:
  productid: '940f8240-1490-0131-24d7-14109fdf482f'
symbian:
  uid: '0xe1cc4e1a'
android:
  version: 2.3.3

extensions: ["rhoconnect-client"]
