---
sdkversion: 5.0.0
name: RE_2.2_Native_JS_API
version: '1.0'
vendor: rhomobile
build: debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator7.1
  provisionprofile: ''
  codesignidentity: iPhone Developer
  entitlements: ''
  BundleIdentifier: com.rhomobile.re2.2nativejsapi
  BundleURLScheme: re2.2nativejsapi
wp8:
  productid: 760c8270-149f-0132-fa51-606720a825c9
android:
  manifest_template: AndroidManifest.erb
  version: 2.3.3
wm: ''
extensions:
- rhoconnect-client
app_type: rhoelements
capabilities: []
