#sdk:   ../../../../rhodes
app_type: rhoelements
sdkversion: 4.0.0
name: JSApp_FSTest
javascript_application: true
version: 1.0
vendor: rhomobile
build: release
bbver: 6.0
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator6.1
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.simpleapp
  BundleURLScheme: simpleapp
wp:
  productid: 'c462d5b0-b351-0130-7980-3caec51bd50e'
symbian:
  uid: '0xe0ac80af'
android:
  version: 2.1

extensions: []

rhohub:
  url: https://appstaging.rhohub.com/api/v1/

#paths:
#  extensions:
#    - C:/projects/Motorola-Extension/extensions
#    - C:/projects/Motorola-Extension/lib/commonAPI

wm:
  webkit_outprocess: 0
