require 'yaml'
cfgfilename = File.join(File.dirname(__FILE__),'config.yml')

if File.file?(cfgfilename)
  config = YAML::load_file(cfgfilename)
  $rho_root = config["rhodes"]
  $rhoconnect_root = config["rhoconnect"]
  $rho_root = File.expand_path($rho_root) if $rho_root
  $rhoconnect_root = File.expand_path($rhoconnect_root) if $rhoconnect_root
end

chdir File.dirname(__FILE__)
namespace :run do
  namespace :android do
    namespace :rb do
      desc "Run Rhoconnect Push Service specs on android device for Ruby rhodes app"
      task :rps do
        ENV['PUSH_TYPE'] = "rhoconnect_push"
        require_relative 'spec_runner'
        exit 1 if $total.to_i==0
        exit $failed.to_i

        # status = exec("mspec android_push_rb_spec.rb")
        # exit status
      end

      desc "Run Google Cloud Messaging specs on android device for Ruby rhodes app"
      task :gcm do
        ENV['PUSH_TYPE'] = "gcm"
        require_relative 'spec_runner'
        exit 1 if $total.to_i==0
        exit $failed.to_i

        # status = exec("mspec android_push_rb_spec.rb 'gcm'")
        # exit status
      end
    end

    namespace :js do
      desc "Run Rhoconnect Push Service specs on android device for JavaScript rhodes app"
      task :rps do
        ARGV[0] = "rhoconnect_push"
        require_relative 'android_push_js_spec.rb'
      end

      desc "Run Google Cloud Messaging specs on android device for JavaScript rhodes app"
      task :gcm do
        ARGV[0] = "gcm"
        require_relative 'android_push_js_spec.rb'
      end
    end
  end
end

