paths:
  extensions:
    - D:\GIT\Motorola-Extensions\build\ci\extensions\
app_type: "rhoelements"
name: "automatic"
capabilities:
  - gps
  - pim
  - camera
  - vibrate
  - phone
  - bluetooth
  - calendar
bbver: 5.0
#- native_browser
#- motorola_browser
applog: "rholog.txt"
version: "1.0.7"
#sdk: c:/Projects/rhodes
vendor: "rhomobile"
iphone:
  emulator: 5.0
  sdk: "iphonesimulator5.1"
  codesignidentity: 
  entitlements: 
  extensions:
    - barcode
    - rainbow
    - digest
    - digest-md5
    - digest-sha1
    - pdf-writer
    - thread
    - nlist
    - digest-sha2
    - openssl.so
    - openssl
    - ezcrypto
#buildcfg: 'Debug'
    - rawsensors
    - audiocapture
    - videocapture
#"rainbow"
#sdk: "MC3000c50b (ARMV4I)"
  entitlements_file: "./production/Entitlements.plist"
#emulator: "Windows Mobile 6.5.3 Professional Emulator"
#use_shared_runtime: 1
  configuration: "Debug"
  production:
    app_plist_title: "SAS"
    app_plist_subtitle: "SAS"
    app_plist_icon_url: "www.sas.com/icon.png"
    app_plist_ipa_url: "www.sas.com/sas.ipa"
    ipa_itunesartwork_image: "./production/image.jpg"
wm:
  extensions:
    - digest
    - digest-md5
    - digest-sha1
    - digest-sha2
    - openssl.so
    - openssl
    - ezcrypto
    - instrumentation
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
win32:
  extensions:
    - digest
    - digest-md5
    - digest-sha1
    - digest-sha2
    - openssl.so
    - openssl
    - ezcrypto
bb:
  extensions:
    - barcode
android:
  extensions:
    - barcode
    - nfc
    - digest
    - digest-md5
    - digest-sha1
    - pdf-writer
    - thread
    - digest-sha2
    - openssl.so
    - openssl
    - ezcrypto
    - rawsensors
    - audiocapture
    - json
    - mspec
    - instrumentation
  capabilities:
    - network_state
    - sdcard
    - calendar
  version: "4.0"
wp:
  productid: "fd55c4d0-51fa-012e-7844-3caec51bd50e"
extensions:
  - json
  - rhoxml
  - rhodes_translator
  - rhoconnect-client
symbian:
  uid: 3780829575
excludedirs:
  bb:
    - "**/*.mp4"
  bb6:
    - "**/*.mp4"
