sdkversion: "4.1.0"
name: "ruby_manual_spec"
version: "1.0"
vendor: "rhomobile"
build: "debug"
applog: "rholog.txt"
app_type: "rhoelements"
iphone:
  configuration: "Release"
  sdk: iphoneos8.3
  provisionprofile: 
  codesignidentity: "iPhone Developer"
  entitlements: 
  BundleIdentifier: "com.rhomobile.rubymanualspec"
  BundleURLScheme: "rubymanualspec"
  extensions:
   - mediaplayer
   - screenorientation
   - mediacapture
wp8:
  productid: "da37e740-9d27-0131-ad03-0023241f0ea9"
  extensions:
   - mediaplayer
   - screenorientation
   - mediacapture
android:
  ajax_api_bridge: false
  version: "4.2.2"
  capabilities:
  extensions:
   - mediaplayer
   - screenorientation
   - mediacapture
   - mobile_payment
wm:
  ajax_api_bridge: false
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions:
   - mediaplayer
   - screenorientation
   - mediacapture
capabilities:
