
# sdkversion: 4.0.0
sdk: "../../../../rhodes"

name: new_orm_spec_js
# app_type: rhoelements
version: 1.0
vendor: rhomobile
build: release
bbver: 4.6
applog: rholog.txt

iphone:
  configuration: Release
  sdk: iphonesimulator6.1
  provisionprofile:
  codesignidentity:
  entitlements:
android:
  version: 4.3

# wm:
#   sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
# wp:
#   productid: 'b6479381-42a8-0130-78de-3caec51bd50e'
# symbian:
#   uid: '0xe1a1ef92'

extensions:
- json

paths:
  extensions:
  - ../../../../../Motorola-Extensions/extensions
