---
sdk: "../../../../rhodes"
name: new_orm_spec_js
applog: RhoLogSpec.txt
version: 1.1

vendor: rhomobile
sdkversion: 4.1

iphone:
  configuration: Release
  sdk: iphonesimulator6.1
  provisionprofile:
  codesignidentity:
  entitlements:
android:
  version: 4.3
  # Not working with 4.4.2!
  # version: 4.4.2

# paths:
#   extensions:
#   - ../../../../rhoconnect-client/ext

extensions:
- json
# - rhoconnect-client
