
# sdkversion: 4.0.0
sdk: "../../../../rhodes"
name: new_orm_spec_js
version: 1.0
vendor: rhomobile
build: release
bbver: 4.6
applog: RhoLogSpec.txt

iphone:
  configuration: Release
  sdk: iphonesimulator6.1
  provisionprofile:
  codesignidentity:
  entitlements:
android:
  version: 4.3
  # Not working with 4.4.2!
  # version: 4.4.2

# paths:
#   extensions:
#   - ../../../../rhoconnect-client/ext

extensions:
- json
# - rhoconnect-client
