sdkversion: "4.1.0"
name: "Intent"
version: "1.0"
vendor: "rhomobile"
build: "debug"
bbver: "6.0"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator7.0"
  provisionprofile: 
  codesignidentity: "iPhone Developer"
  entitlements: 
  BundleIdentifier: "com.rhomobile.intent"
  BundleURLScheme: "Intent"
wp:
  productid: "24ef94f0-4924-0131-3982-548564a893b0"
symbian:
  uid: "0xeccfc52a"
android:
  version: "2.3.3"
extensions:
  - rhoconnect-client
app_type: "rhoelements"
capabilities: 
