#sdkversion: "3.5.0"
#sdk: c:/projects/rhodes
name: "RhodesTestApp"
#motorola_license_company: "Motorola Test and Validation"
#motorola_license: "0277106A081D151A000307771A7E1C75"
#motorola_license: "`OLrrql(`iVCdNt=PJ1DH=jKVc5O@ixKTtEMTWDVSQO@D2CnbLU@_)K(DvBALrln`WjnL@0n/[FLHhj$KEs.C?x)c(O6dju{2yA(;s;`"
version: "1.0"
vendor: "rhomobile"
build: "debug"
bbver: "4.6"
applog: "rholog.txt"
#rhohub:
#  url: "https://appstaging.rhohub.com/api/v1/"
#connection:
#  proxy: "http://wwwgate0.mot.com:1080"
iphone:
  configuration: "Release"
  sdk: iphonesimulator8.1
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.retestapp"
  BundleURLScheme: "retestapp"
  emulatortarget: "iphone"
wp8:
  ajax_api_bridge: false
  productid: "dc201bf1-e2e9-012f-10dc-00216a8a58d0"
  extensions: ["json", "digest", "digest-md5", "digest-sha1", "uri", "barcode"] # "digest-sha2", "openssl", "mediacapture",
wm:
  extensions:
    - digest
    - digest-md5
    - digest-sha1
    - digest-sha2
    - openssl.so
    - openssl
    - ezcrypto
    - rhoconnect-client
#mapping: yes
#sdk: "MC3000c50b (ARMV4I)"
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
symbian:
  uid: "0xe01c7e9f"
android:
  extensions:
    - barcode
    #- rainbow
    - nfc
    - digest
    - digest-md5
    - digest-sha1
    - pdf-writer
    - thread
    - digest-sha2
    - openssl.so
    - openssl
    - ezcrypto
#- rawsensors
    - audiocapture
#- rhoconnect-client
  capabilities:
    - network_state
    - sdcard
    - calendar
  version: "4.2.2"
extensions:
  - json
  - rhoxml
  - rhodes_translator
  - rhoconnect-client
app_type: "rhoelements"
capabilities:
  - gps
  - pim
  - camera
  - vibrate
  - phone
  - bluetooth
  - calendar
