---
sdkversion: 5.0.0
name: RE_2.2_Compliance_semiauto
version: '1.0'
vendor: rhomobile
build: debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator8.0
  provisionprofile: ''
  codesignidentity: iPhone Developer
  entitlements: ''
  BundleIdentifier: com.rhomobile.re2.2compliancesemiauto
  BundleURLScheme: re2.2compliancesemiauto
  production:
    ipa_itunesartwork_image: ./production/iTunesArtwork.png
wp8:
  productid: e5d44791-b367-0132-bfbe-548564b37e45
android:
  version: 2.3.3
  abis: [arm, x86]
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
wm: ''
extensions:
- rhoconnect-client
app_type: rhoelements
capabilities: []
