name: "SelectiveBulkSync"
version: 1.0
vendor: "rhomobile"
build: "debug"
bbver: 4.6
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator5.0"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.selectivebulksync"
  BundleURLScheme: "selectivebulksync"
wm:
#sdk: "MC3000c50b (ARMV4I)"
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
wp:
  productid: "794f3c91-c930-012f-923d-58946b66d410"
symbian:
  uid: "0xe43acafa"
android:
  version: 2.3.3
  emulator: "Amit"
extensions:
  - json
  - rhoconnect-client
capabilities:
  - motorola_browser
