sdkversion: "5.0.0"
name: "camera_app"
version: "1.0"
vendor: "rhomobile"
build: "debug"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphoneos8.2"
  provisionprofile: 
  codesignidentity: "iPhone Developer"
  entitlements: 
  BundleIdentifier: "com.rhomobile.cameraapp"
  BundleURLScheme: "cameraapp"
  production:
    ipa_itunesartwork_image: "./production/iTunesArtwork.png"
wp8:
  productid: "d35fe920-8dd1-0132-ad1f-0023241f0ea9"
  extensions:
    - mediacapture
android:
  manifest_template: "AndroidManifest.erb"
  version: "2.3.3"
  logcatFilter: "APP:I StrictMode:I DEBUG:I *:E"
wm: 
win32:
  deployqt: "1"
  deploymsvc: "1"
extensions:
  - mediacapture
app_type: "rhoelements"
capabilities:
