#sdk: /Users/MOHUS/rhodes
paths:
  extensions:
  - ../common_api_spec/extensions/
  - ../../feature_def/auto_common_spec/extensions/
  
sdk: ../../../../rhodes
sdkversion: 3.3.2
name: common_api_spec
version: 1.0

#app_type: rhoelements

vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator7.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.commonapispec
  BundleURLScheme: commonapispec
  extensions: ["entityGen"]
wp:
  productid: 'b6479381-42a8-0130-78de-3caec51bd50e'
symbian:
  uid: '0xe1a1ef92'
android:
  version: 2.1

extensions: ["json", "rhospec", "megamodule", "simpleonlystaticmodule"]
