name: "JS_SyncEngineAPITest"
capabilities:
  - gps
  - pim
  - camera
  - vibrate
  - phone
  - bluetooth
  - calendar
  - motorola_browser
#- push
#- non_motorola_device
#- motorola_browser
#sdkversion: "3.3.3"
extensions:
  - json
  - rhoconnect-client
version: "1.0.7"
vendor: "rhomobile"
bbver: "4.6"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator6.1"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.rhomobileapplication4"
  BundleURLScheme: "rhomobileapplication4"
wp:
  productid: "2c0c3bd1-7fd5-012f-3a09-70f395d08c2c"
symbian:
  uid: "0xea8a3ffb"
wm:
  extensions:
    - digest
    - digest-md5
    - digest-sha1
#push:
#sender: "tnvmoto@gmail.com"
#- rhoconnect-push
#- non_motorola_device
#- motorola_browser
  #sdk: "MC3000c50b (ARMV4I)"
#sdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
android:
  extensions:
    - rainbow
    - digest
    - digest-md5
    - digest-sha1
    - pdf-writer
    - thread
  capabilities:
#- push
    - network_state
    - sdcard
    - calendar
    - vibrate
  version: "2.3.3"
  emulator: "Amit"
