#sdk: "C:/DevelopmentTools/rhomobile/rhodes" 
paths:
  extensions:
#  - C:/DevelopmentTools/rhomobile/rhodes/lib/extensions
#  - C:/DevelopmentTools/rhomobile/rhodes/lib
#  - C:/DevelopmentTools/rhomobile/Motorola-Extensions/lib/commonAPI
#  - C:/DevelopmentTools/rhomobile/rhoconnect-client/ext
#  - C:/DevelopmentTools/rhomobile/Motorola-Extensions/extensions/
  - C:/DevelopmentTools/rhomobile/Motorola-Extensions/build/ci/extensions
#  - C:/Users/fpc843/workspace/fpc843_rhoelements_dev/NEON/R2D1/RhoElementsOneExtension/extensions
#  neon: C:/Users/fpc843/workspace/fpc843_rhoelements_dev/NEON

sdkversion: 4.0.0
name: performance_spec
app_type: rhoelements
version: 1.0
vendor: rhomobile
build: debug
debug: 1
bbver: 6.0
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator6.1
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.teststartup
  BundleURLScheme: teststartup
wp:
  productid: '787da1d0-88dd-0130-26dd-00ffb02bf306'
symbian:
  uid: '0xef4db7d5'
android:
  version: 2.1
  extensions: ["barcode"]
  capabilities:
  - native_browser
  - motoroladev
wm:
  #use_shared_runtime: yes
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions: ["barcode"]
#capabilities:
#- non_motorola_device
