paths:
  extensions:
#  - C:/DevelopmentTools/rhomobile/rhodes/lib/extensions
#  - C:/DevelopmentTools/rhomobile/Motorola-Extensions/extensions
#  - C:/DevelopmentTools/rhomobile/Motorola-Extensions/lib/commonAPI
#  - C:/DevelopmentTools/rhomobile/rhoconnect-client/ext
#  - C:/DevelopmentTools/rhomobile/Motorola-Extensions/build/ci/extensions
#  - C:/DevelopmentTools/rhomobile/Motorola-Extensions/build/ci/extensions/instrumentation/extensions
#  - C:/Neon/git/Motorola-Extensions/build/ci/extensions/instrumentation/extensions
# DCC - This path MUST be removed prior to check in
    - C:/Neon/git/Motorola-Extensions/lib/commonAPI
    - C:/Neon/git/rhoconnect-client/ext
#end DCC
#  - B:/git/Motorola-Extensions/build/ci/extensions/instrumentation/extensions
#  - C:/Neon/git/Motorola-Extensions/build/ci/extensions/instrumentation/extensions
# neon:
#  - C:/Users/fpc843/workspace/fpc843_rhoelements_dev/NEON
app_type: "rhoelements"
name: "CommonManual"
capabilities:
  - gps
  - pim
  - camera
  - vibrate
  - phone
  - bluetooth
  - calendar
bbver: 5.0
#- native_browser
#- motorola_browser
applog: "rholog.txt"
version: "1.0.7"
#sdk: c:/Projects/rhodes
vendor: "rhomobile"
iphone:
  emulator: 5.0
  sdk: "iphonesimulator8.1”
  codesignidentity: 
  entitlements: 
  extensions:
    - barcode
    - digest
    - digest-md5
    - digest-sha1
    - pdf-writer
    - thread
    - nlist
    - digest-sha2
    - openssl.so
    - openssl
    - ezcrypto
#buildcfg: 'Debug'
    - rawsensors
    - audiocapture
    - videocapture
#"rainbow"
#sdk: "MC3000c50b (ARMV4I)"
  entitlements_file: "./production/Entitlements.plist"
#emulator: "Windows Mobile 6.5.3 Professional Emulator"
#use_shared_runtime: 1
  configuration: "Debug"
  production:
    app_plist_title: "SAS"
    app_plist_subtitle: "SAS"
    app_plist_icon_url: "www.sas.com/icon.png"
    app_plist_ipa_url: "www.sas.com/sas.ipa"
    ipa_itunesartwork_image: "./production/image.jpg"
wm:
  extensions:
#    - digest
#    - digest-md5
#    - digest-sha1
#    - digest-sha2
#    - openssl.so
#    - openssl
#    - ezcrypto
#    - json
    - barcode
    - Coreapi
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
win32:
  extensions:
    - digest
    - digest-md5
    - digest-sha1
    - digest-sha2
    - openssl.so
    - openssl
    - ezcrypto
bb:
  extensions:
    - barcode
android:
  extensions:
    - barcode
    - nfc
    - digest
    - digest-md5
    - digest-sha1
    - pdf-writer
    - thread
    - digest-sha2
    - openssl.so
    - openssl
    - ezcrypto
    - rawsensors
    - audiocapture
  capabilities: 
  version: "4.0"
wp:
  productid: "fd55c4d0-51fa-012e-7844-3caec51bd50e"
extensions:
  - json
  - rhoxml
  - rhodes_translator
  - rhoconnect-client
symbian:
  uid: 3780829575
excludedirs:
  bb:
    - "**/*.mp4"
  bb6:
    - "**/*.mp4"
