#sdk: e:\win7_git\rhodes
app_type: "rhoelements"
sdkversion: "3.5.0"
name: "Only_readsdcard"
version: 1.0
vendor: "rhomobile"
build: "release"
bbver: 4.6
applog: "rholog.txt"
#capabilities:
#- vibrate
rhohub:
  url: "https://appstaging.rhohub.com/api/v1/"
connection:
  proxy: http://wwwgate0.mot.com:1080
iphone:
  ajax_api_bridge: false
  configuration: "Release"
  sdk: "iphonesimulator8.1”
  provisionprofile: 
  codesignidentity: 
  entitlements: 
#extensions: ["sensor", "signature", "barcode", "mediaplayer", "mediacapture"]
  extensions:
    - sensor
    - barcode
    - mediaplayer
    - screenorientation
  BundleIdentifier: "manual_common_spec"
  BundleURLScheme: "manual_common_spec"
wp:
  ajax_api_bridge: false
  productid: "fa586990-6e21-0130-bf9e-3c075409010c"
#extensions: ["signature", "barcode", "mediaplayer", "sensor"]
symbian:
  uid: "0xeeceaf9f"
#sdk: "MC3000c50b (ARMV4I)"
android:
  version: "4.2.2"
  extensions:
    - printing
    - printing_zebra
#abis: ["x86"]
#javascript_application: true
#sdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
#sdk: "MC3000c50b (ARMV4I)"
wm:
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions:
    - printing
#javascript_application: true
    - printing_zebra
paths:
  extensions: 
minify:
  js: false
  css: false
