name: ruby_auto_spec
app_type: rhoelements
version: 1.0
vendor: rhomobile
build: release
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator8.1
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.rubyautospec
  BundleURLScheme: rubyautospec
wp8:
  productid: 'b6479381-42a8-0130-78de-3caec51bd50e'
android:
  version: 4.2.2
  capabilities:
  - native_browser
wp8:
  extensions:
   - digest
   - digest-sha1
   - digest-md5
   - json
   - uri
