name: "rhoconnectpush_8675"
bbver: 6.0
applog: "rholog.txt"
version: "1.0.0"
vendor: "rhomobile"
capabilities:
  - vibrate
  - phone
  - motorola_browser
extensions:
  - rhoconnect-client
  - rhoconnect-push
android:
  capabilities:
    - sdcard
    - phone
#  push:
#    notifications: "background"
  version: 2.3.3
  emulator: "Amit"
wm:
  #sdk: "MC3000c50b (ARMV4I)"
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"  
