sdkversion: "3.3.2"
name: "stressapp"
version: 1.0
vendor: "rhomobile"
build: "release"
bbver: 4.6
applog: "rholog.txt"
app_type: "rhoelements"
iphone:
  configuration: "Release"
  sdk: iphoneos8.2
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.stressapp"
  BundleURLScheme: "stressapp"
  extensions:
    - nativeBridgeTest
    - barcode
    - genCallbackTests
    - appEvents
    - indicators
    - sensor
    - screenorientation
    - audiocapture
    - mediaplayer
wp:
  productid: "b6479381-42a8-0130-78de-3caec51bd50e"
android:
  version: "4.2.2"
  extensions:
    - nativeBridgeTest
    - barcode
    - screenorientation
    - instrumentation
    - cardreader
    - indicators
    - sensor
    - websocket
    - eventsource
    - audiocapture
    - screenorientation
    - mediaplayer
  capabilities:
    - native_browser
wm:
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions:
    - barcode
    - screenorientation
    - instrumentation
    - cardreader
    - indicators
    - sensor
    - audiocapture
    - smartCradle
    - mediacapture
    - mediaplayer
extensions:
  - genPropBag
  - logCapture
