#sdk: "../../../rhodes"
sdkversion: "3.5.0"
name: "clientapi"
version: 1.0
vendor: "rhomobile"
build: "release"
bbver: 4.6
app_type: "rhoelements"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator8.1"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
wp:
  productid: "0b698de0-7218-0130-547c-001a925f2369"
symbian:
  uid: "0xef6036c4"
android:
  version: "4.2.2"
  capabilities:
    - hardware_acceleration
wm:
  #extensions: ["digest", "digest-md5", "digest-sha1", "digest-sha2", "openssl.so", "openssl", "ezcrypto"]
  #"rainbow"
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  #emulator: "Windows Mobile 6.5.3 Professional Emulator"
  #use_shared_runtime: 1
#paths:
  #extensions: "../../ext"
extensions:
  - json
  - rhoconnect-client
motorola_license_company: 'Motorola Test and Validation'
motorola_license: '0277106A081D151A000307771A7E1C75'

