#sdk: c:/work/rhodes
app_type: "rhoelements"
sdkversion: "3.5.0"
name: "manual_common_spec"
version: 1.0
vendor: "rhomobile"
build: "release"
bbver: 4.6
applog: "rholog.txt"
capabilities:
  - pim
  - vibrate

iphone:
  ajax_api_bridge: false
  sdk: "iphonesimulator8.1"
  configuration: "Release"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  extensions:
    - sensor
    - barcode
    - mediaplayer
    - screenorientation
    - mediacapture
  BundleIdentifier: "com.rhomobile.manualcommonspec"
  BundleURLScheme: "manualcommonspec"

wp8:
  ajax_api_bridge: false
  productid: "fa586990-6e21-0130-bf9e-3c075409010c"
  extensions: ["barcode"]

symbian:
  uid: "0xeeceaf9f"

android:
  no_compression: [pdf, png, html, js, css]
  ajax_api_bridge: false
  version: "4.0.3"
  manifest_template: AndroidManifest.erb
  extensions:
    - emdk3-manager
    - barcode
    - mediaplayer
    - sensor
    - mediacapture

wm:
  #webkit_outprocess: 1
  ajax_api_bridge: false
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions:
    - barcode
    - mediaplayer
    - indicators
    - sensor
    - smartCradle
    - mediacapture

#paths:
#  extensions:
#    - C:/work/Motorola-Extensions/extensions
#    - C:/work/Motorola-Extensions/lib/commonAPI

#minify:
#  js: false
#  css: false

#cloud:
#  server_url:
#    - https://rhohub-test-cedar.herokuapp.com 
#    - https://rmsstaging.rhomobile.com/api/v1
#    - https://rms.rhomobile.com/api/v1
