#sdk: c:/projects/rhodes
app_type: "rhoelements"
sdkversion: "3.5.0"
name: "manual_common_spec"
version: 1.0
vendor: "rhomobile"
build: "release"
bbver: 4.6
applog: "rholog.txt"
capabilities:
- pim
- vibrate
iphone:
  ajax_api_bridge: false
  sdk: "iphonesimulator8.1"
  configuration: "Release"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
#extensions: ["sensor", "signature", "barcode", "mediaplayer", "mediacapture"]
  extensions:
    - sensor
    - barcode
    - mediaplayer
    - screenorientation
  BundleIdentifier: "com.rhomobile.manualcommonspec"
  BundleURLScheme: "manualcommonspec"
wp:
  ajax_api_bridge: false
  productid: "fa586990-6e21-0130-bf9e-3c075409010c"
#extensions: ["signature", "barcode", "mediaplayer", "sensor"]
symbian:
  uid: "0xeeceaf9f"
#sdk: "MC3000c50b (ARMV4I)"
android:
  no_compression: [pdf, png, html, js, css]
  ajax_api_bridge: false
  version: "4.0.3"
  extensions:
    - barcode
    - mediaplayer
#  - ../../../../Motorola-Extensions/build/ci/extensions
#  - ../../../../Motorola-Extensions/lib/commonAPI
    - sensor
  manifest_template: AndroidManifest.erb
#security_token: "123"
wm:
  #webkit_outprocess: 1
  ajax_api_bridge: false
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions:
    - barcode
    - mediaplayer
    - indicators
    - sensor
    - smartCradle

#minify:
#  js: false
#  css: false
