#sdk: "c:/projects/rhodes"
app_type: rhoelements
sdk:   ../../../../rhodes
sdkversion: 3.5.0
name: manual_common_spec
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator6.1
  extensions: ["signature", "barcode"]
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: manual_common_spec
  BundleURLScheme: manual_common_spec
wp:
  productid: 'fa586990-6e21-0130-bf9e-3c075409010c'
symbian:
  uid: '0xeeceaf9f'
android:
  version: 4.0.3
  extensions: ["signature", "barcode"]
wm:
  extensions: ["barcode"]

paths:
  extensions:
  - ../../../../Motorola-Extensions/build/ci/extensions
  - ../../../../Motorola-Extensions/lib/commonAPI

