#sdk: c:/work/rhodes
app_type: "rhoelements"
sdkversion: "3.5.0"
name: "manual_common_spec_beta12"
version: 1.0
vendor: "rhomobile"
build: "release"
bbver: 4.6
applog: "rholog.txt"
capabilities:
- pim
- vibrate
iphone:
  configuration: "Release"
  sdk: "iphonesimulator6.1"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
#extensions: ["sensor", "signature", "barcode", "mediaplayer", "mediacapture"]
  extensions:
    - sensor
    - barcode
    - mediaplayer
    - screenorientation
  BundleIdentifier: "manual_common_spec"
  BundleURLScheme: "manual_common_spec"
wp:
  productid: "fa586990-6e21-0130-bf9e-3c075409010c"
#extensions: ["signature", "barcode", "mediaplayer", "sensor"]
symbian:
  uid: "0xeeceaf9f"
#sdk: "MC3000c50b (ARMV4I)"
android:
  version: "4.0.3"
  extensions:
    - barcode
    - mediaplayer
#  - ../../../../Motorola-Extensions/build/ci/extensions
#  - ../../../../Motorola-Extensions/lib/commonAPI
    - sensor
#security_token: "123"
wm:
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions:
    - barcode
    - mediaplayer
    - indicators
    - sensor
paths:
  extensions: 
