#sdk: ../../../../rhodes
paths:
  extensions:

# Please use relative pathes

  - ../extensions
#  - ../../../../Motorola-Extensions/lib/commonAPI
#  - ../../../../rhoconnect-client/ext/

#  neon:
#  - C:/Users/fpc843/workspace/fpc843_rhoelements_dev/NEON

sdkversion: 3.3.2
name: Native Test Harness
app_type: rhoelements
version: 1.0
vendor: rhomobile
build: release
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator7.1
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.nativetestharness
  BundleURLScheme: nativetestharness
  extensions: ["nativeBridgeTest", "barcode", "genCallbackTests", "appEvents", "indicators", "sensor", "screenorientation", "audiocapture"]
wp:
  productid: 'b6479381-42a8-0130-78de-3caec51bd50e'
symbian:
  uid: '0xe1a1ef92'
android:
  version: 4.2.2
  extensions: ["Printing", "Printing_Zebra", "nativeBridgeTest", "barcode", "screenorientation", "instrumentation", "cardreader", "indicators", "sensor", "websocket", "eventsource", "audiocapture", 'screenorientation']  
  capabilities:
  - native_browser
wm:
  #webkit_outprocess: 1
  #use_shared_runtime: yes
  #sdk: MC3000c50b (ARMV4I)
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions: ["instrumentation", "Printing", "Printing_Zebra"]
#capabilities:
#- non_motorola_device

extensions: ["genPropBag", "logCapture", "instrumentation"]
