#sdk: ../../../../rhodes
paths:
  extensions:

# Please use relative pathes

  - ../auto/feature_def/auto_common_spec/extensions
  - ../extensions
#  - ../../../../Motorola-Extensions/lib/commonAPI
#  - ../../../../rhoconnect-client/ext/

#  neon:
#  - C:/Users/fpc843/workspace/fpc843_rhoelements_dev/NEON

sdkversion: 3.3.2
name: Native Test Harness
app_type: rhoelements
version: 1.0
vendor: rhomobile
build: release
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator7.1
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.nativetestharness
  BundleURLScheme: nativetestharness
  extensions: ["nativeBridgeTest", "barcode", "genCallbackTests", "appEvents", "indicators", "sensor", "screenorientation", "audiocapture"]
wp8:
  productid: 'b6479381-42a8-0130-78de-3caec51bd50e'
  sdk: ../../rhodes
  # WP8 uses specific branch therefore build from source
symbian:
  uid: '0xe1a1ef92'
android:
  version: 4.2.2
  # "simulscan"
  # "symbolDevice"
  extensions: ["nativeBridgeTest", "instrumentation", "Printing", "Printing_Zebra", "barcode", "screenorientation", "cardreader", "indicators", "sensor", "websocket", "eventsource", "audiocapture", 'screenorientation', 'rhoconnect-client', "mediaPlayer", "json", "rhodes_translator", "digest", "digest-md5", "digest-sha1", "pdf-writer", "thread", "rhoconnect-push", "nfc", "openssl.so", "digest-sha2", "genPropBag", "logCapture"]  
  capabilities:
  - native_browser
  - network_state
  - sdcard
  - calendar
  - vibrate
  - gps
  - pim
  - camera
  - vibrate
  - phone
  - bluetooth
  - calendar
wm:
  #webkit_outprocess: 1
  #use_shared_runtime: yes
  #sdk: MC3000c50b (ARMV4I)
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
#  extensions: ["instrumentation", "Printing", "Printing_Zebra", "audiocapture"]
  extensions: ["nativeBridgeTest", "instrumentation", "Printing", "Printing_Zebra", "barcode", "screenorientation", "cardreader", "indicators", "sensor", "audiocapture", 'screenorientation', 'rhoconnect-client', "mediaPlayer", "json", "rhodes_translator", "digest", "digest-md5", "digest-sha1", "pdf-writer", "thread", "rhoconnect-push", "nfc", "openssl.so", "digest-sha2", "genPropBag", "logCapture"]  
#capabilities:
#- non_motorola_device

# Removed these temporarily... they seem to be part of the auto_common_spec project (the Rho extensions are in that app)... they should be part of RMS-Testing like the instrumentation extension.
#extensions: ["genPropBag", "logCapture"]
