app_type: rhoelements
sdkversion: 4.0.0
name: Multiapp2
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator7.1
  extensions: ["sensor", "signature", "barcode", "mediaplayer"]
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: Multiapp2
  BundleURLScheme: Multiapp2
wp:
  productid: 'fa586990-6e21-0130-bf9e-3c075409010c'
symbian:
  uid: '0xeeceaf9f'
android:
  version: 4.2.2
  extensions: ["signature", "barcode", "mediaplayer", "sensor"]
wm:
  #sdk: "MC3000c50b (ARMV4I)"
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions: ["barcode", "mediaplayer", "indicators", "sensor"]

paths:
  extensions:
#  - ../../../../Motorola-Extensions/build/ci/extensions
#  - ../../../../Motorola-Extensions/lib/commonAPI

#security_token: "123"


