#sdkversion: "4.1.0"
name: "compliancetest_ruby"
version: 1.0
vendor: "rhomobile"
build: "debug"
applog: "rholog.txt"
app_type: "rhoelements"
iphone:
  configuration: "Release"
  sdk: iphoneos8.2
  provisionprofile: 
  codesignidentity: "iPhone Developer"
  entitlements: 
  BundleIdentifier: "com.rhomobile.compliancerubytest"
  BundleURLScheme: "compliancerubytest"
  extensions:
   - audiocapture
   - barcode
   - cardreader
   - indicators
   - mediacapture
   - mediaplayer
   - printing
   - printing_zebra
   - screenorientation
   - signature
   - sensor
wp8:
  productid: "da37e740-9d27-0131-ad03-0023241f0ea9"
  extensions:
   - barcode
   - mediacapture
android:
  ajax_api_bridge: false
  version: "4.2.2"
  extensions:
   - audiocapture
   - barcode
   - cardreader
   - indicators
   - mediaplayer
   - mediacapture
   - printing
   - printing_zebra
   - screenorientation
   - signature
   - sensor
wm:
  ajax_api_bridge: false
  extensions:
   - audiocapture
   - barcode
   - cardreader
   - indicators
   - mediacapture
   - mediaplayer
   - printing
   - printing_zebra
   - screenorientation
   - signature
   - sensor
