---
devices:
- uri: 10.233.82.45:37579
  name: iPhone
  platform: APPLE
  application: new_orm_spec_js
  enabled: true
- uri: 192.168.150.20:37579
  name: localhost
  platform: ANDROID
  application: new_orm_spec_js
  enabled: true
webserver:
  documentRoot: /var/folders/jt/9tm6qh6x105953s8vm0hs5p80000gn/T/d20150915-77606-hg97o8
last_bundle_key: 89
